# Setup
title:               Hydejack

# The unique resource location of your page.
# Set to `https://<username>.github.io` when hosting on GitHub pages (and not using custom domains!)
url:                 https://qwtel.com

# Set to '' when hosting a blog on GitHub pages, like `//<username>.github.io`
# Set to '/<reponame>' when using the `gh-pages` branch of a repository
baseurl:             /hydejack

# A short description for the page title (browser tab)
tagline:             A pretentious two-column Jekyll theme.

# A longer description of the page, used in the sidebar, and as fallback for the meta description tag.
# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  A pretentious two-column [Jekyll](http://jekyllrb.com/) theme, stolen by
  [`@qwtel`{:style="background: rgba(255, 255, 255, 0.15)" rel="me"}](https://twitter.com/qwtel) from
  [Hyde](http://hyde.getpoole.com).
  You could say it was.. [hydejacked](http://media3.giphy.com/media/makedRIckZBW8/giphy.gif).

# See also: `_data/authors.yml`
author:
  name: Florian Klampfer
  email: f.klampfer@gmail.com
  authors_key: me # the key of this author in `_data/authors.yml`

# Fallback image and color if not overwritten
image:               /hydejack/assets/img/nap.jpg
color:               '#A85641'

# Fonts
font_heading:        "'Roboto Slab', Helvetica, Arial, sans-serif"
font:                "'Noto Serif', Georgia, serif"

# Remove to disable Google Fonts
google_fonts:        Roboto+Slab:700|Noto+Serif:400,400i,700,700i

# Remove to disable Google Anaylics
google_analytics:    UA-84025722-2

# Setting a disqus subdomain will enable the comment section
disqus_shortname:    qwtel

copyright:           '&copy; 2017. All rights reserved.'

# Set to true when building locally with the `--lsi` option
# See: https://jekyllrb.com/docs/variables/#site-variables, `site.related_posts`
use_lsi:             false

# Set to true if you want to show an icon after every link that points to an external site
mark_external:       true

# ======================
# Hydejack configuration
# ======================
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

permalink:           pretty

paginate:            5
paginate_path:       '/page-:num/'

collections:
  featured_categories:
    permalink:       /category/:name/
    output:          true
  featured_tags:
    permalink:       /tag/:name/
    output:          true
  projects:
    permalink:       /projects/:path/
    output:          true

exclude:             [node_modules, README.md, package.json, resume.json]

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed

# If you are updating form a previous verison of Hydejack, uncomment this line below,
# so that existing subscribers to your feed continue to receive updates.
# feed:
#   path: atom.xml
