# Setup
title:               Hydejack

url:                 https://qwtel.com

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             /hydejack

# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

collections:
  projects:
    permalink:       /projects/:path/
    output:          true

exclude:             [node_modules, package.json, README.md, LICENSE.md]

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed

version:             6.0.0-alpha
