# Setup
title:               Hydejack

url:                 https://qwtel.com

# Set to '' when hosting a blog on GitHub pages, like `//<username>.github.io`
# Set to '/<reponame>' when using the `gh-pages` branch of a repository
baseurl:             /hydejack

# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

permalink:           pretty

paginate:            5
paginate_path:       '/page-:num/'

collections:
  tags:
    permalink:       /tag/:name/
    output:          true
  projects:
    permalink:       /projects/:path/
    output:          true

exclude:             [node_modules, package.json, README.md, LICENSE.md]

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed

version:             6.0.0-alpha
